import { computed, ref, watch } from "vue";

const STORAGE_KEY = "realtime-kanban:language";

const messages = {
  en: {
    nav: {
      boards: "Boards",
      board: "Board",
      activity: "Activity",
      members: "Members",
      settings: "Settings",
      profile: "Profile",
      ai: "AI"
    },
    common: {
      signIn: "Sign in",
      createAccount: "Create account",
      forgotPassword: "Forgot password",
      signOut: "Log out",
      save: "Save",
      saving: "Saving...",
      close: "Close",
      cancel: "Cancel",
      working: "Working...",
      error: "Error",
      invite: "Invite",
      undo: "Undo",
      redo: "Redo",
      open: "Open",
      create: "Create",
      remove: "Remove",
      revoke: "Revoke",
      delete: "Delete",
      transfer: "Transfer",
      chooseAvatar: "Choose avatar",
      clearAvatar: "Clear avatar",
      noFileSelected: "No file selected",
      descriptionOptional: "Description optional",
      selectBoardMember: "Select a board member",
      selectFirst: "Select a card first",
      logoutFailed: "Logout failed",
      unreadNotifications: "{count} unread notifications"
    },
    auth: {
      signInTitle: "Sign in",
      signInBody: "Sign in with Supabase auth to enter your workspace.",
      registerTitle: "Create account",
      registerBody: "Creates a Supabase auth account. public.handle_new_user() should create the profile row.",
      forgotTitle: "Reset password",
      forgotBody: "Requests a Supabase password reset email.",
      inviteTitle: "Accept invitation",
      inviteBody: "Sign in with the invited email, then accept the board invitation.",
      formNote: "This calls Supabase auth. No local mock users are created.",
      ownerFullAccess: "Owner: full access",
      editorCardsOnly: "Editor: cards only",
      viewerReadOnly: "Viewer: read-only",
      email: "Email",
      password: "Password",
      name: "Name",
      resetSent: "Check your email for a password reset link.",
      invitationAccepted: "Invitation accepted.",
      invalidLogin: "Invalid email or password.",
      accountExists: "An account with that email already exists.",
      authFailed: "Authentication failed. Please try again.",
      inviteFailed: "Could not accept the invitation. Please sign in with the invited email."
    },
    boards: {
      header: "Workspace Dashboard",
      title: "Your boards",
      summary: "Boards shown here are loaded from Supabase membership rows. Empty workspaces stay empty until you create a board.",
      setupRequired: "Supabase setup required",
      setupRequiredBody: "Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY, then reload the app. VITE_SUPABASE_PUBLISHABLE_KEY is supported as a fallback.",
      profileSetup: "Profile setup needs attention",
      boardsLoadFailed: "Boards could not be loaded",
      noBoards: "No boards yet",
      noBoardsBody: "Create a board to insert a Supabase board, owner membership, and default columns.",
      createTitle: "New board",
      createBody: "Creates the board, owner membership, and Todo / In Progress / Review / Done columns.",
      openBoard: "Open board",
      createBoard: "Create board",
      recentActivity: "Recent activity",
      noRecentActivity: "No recent activity",
      noRecentActivityBody: "Activity appears after Supabase writes create log rows."
    },
    board: {
      notFound: "Board not found",
      workSurface: "Board work surface",
      loading: "Loading board",
      loadingBody: "Reading board, columns, cards, members, and activity from Supabase.",
      noColumns: "No columns yet",
      noColumnsBody: "This board has no Supabase column rows.",
      createDefaultColumns: "Create default columns",
      searchPlaceholder: "Search cards",
      allAssignees: "All assignees",
      allLabels: "All labels",
      allStatuses: "All statuses",
      titleField: "Title",
      descriptionField: "Description",
      columnField: "Column",
      assigneeField: "Assignee",
      labelsField: "Labels",
      addCard: "Add card",
      unassigned: "Unassigned",
      newCardTitle: "New card title",
      newCardDescription: "What needs to happen?",
      labelsPlaceholder: "frontend, urgent",
      statusActive: "active",
      statusBlocked: "blocked",
      statusDone: "done",
      taskDetail: "Task detail",
      selectTask: "Select a task",
      outdatedEditDetected: "Outdated edit detected",
      draftBasedOnVersion: "Your draft was based on version {mine}. Latest is version {latest}.",
      keepMine: "Keep mine",
      acceptLatest: "Accept latest",
      checklist: "Checklist",
      noChecklistItems: "No saved checklist items yet.",
      comments: "Comments",
      addComment: "Add comment",
      addCommentPlaceholder: "Add a comment",
      history: "History",
      cardHistoryRecorded: "Card history is recorded in activity logs.",
      noCardsHere: "No cards here",
      createCardHint: "Create a card or move an existing Supabase card into {column}.",
      viewerReadOnlyShort: "Viewer role is read-only. Card actions are disabled.",
      online: "ONLINE",
      offlinePrefix: "OFFLINE",
      connectionRestored: "Connection restored. Queue is syncing.",
      connectionLost: "No connection. New actions will queue.",
      versionConflict: "Version conflict: the card was changed by another user",
      cardMoveFailed: "Card move failed",
      cardCreationFailed: "Card creation failed",
      cardQueuedOffline: "Card queued offline",
      cardSaveFailed: "Card save failed",
      changeQueuedOffline: "Change queued offline",
      deleteQueuedOffline: "Delete queued offline",
      commentFailed: "Comment failed",
      commentAdded: "Comment added",
      commentUpdated: "Comment updated",
      commentDeleted: "Comment deleted",
      status: "Status",
      saveCard: "Save card",
      deleteCard: "Delete",
      noCardSelected: "No card selected",
      viewerReadOnly: "Viewer role is read-only. Editing, deleting, moving, and comments are disabled."
    },
    settings: {
      title: "Operational controls for {board}.",
      subtitle: "Only data backed by the provided Supabase schema is marked connected.",
      systemControlCenter: "Realtime System Control Center",
      boardSection: "Board",
      invitationsSection: "Invitations",
      permissionsSection: "Permissions",
      localizationSection: "Localization",
      realtimeSection: "Realtime",
      workspaceIdentity: "Workspace identity",
      pendingAccess: "Pending access",
      roleEnforcement: "Role enforcement",
      interfaceLanguage: "Interface language",
      languageEnglish: "English",
      languageRussian: "Russian",
      languageEnglishDetail: "Interface in English",
      languageRussianDetail: "Interface in Russian",
      languagePreference: "Language preference is stored locally.",
      liveSync: "Live sync channel",
      conflictStrategy: "Conflict strategy",
      conflictStrategyVersioned: "Versioned last-write-wins with rollback",
      conflictStrategyManual: "Manual conflict review",
      conflictStrategyServer: "Server authority mode",
      conflictStrategyVersionedDetail: "Prefer the latest version with rollback support",
      conflictStrategyManualDetail: "Show a manual review state when writes collide",
      conflictStrategyServerDetail: "Let the server decide the final write",
      realtime: "Realtime",
      realtimeProvider: "Provider",
      realtimeStatus: "Sync status",
      realtimePresence: "Presence",
      realtimeLive: "Supabase Realtime",
      realtimeFallback: "Local BroadcastChannel fallback",
      boardUrl: "Board URL",
      privateToMembers: "Private to members",
      synced: "SYNCED",
      connected: "CONNECTED",
      versioned: "VERSIONED",
      languageSynced: "LANGUAGE SYNCED",
      rlsRequired: "RLS POLICY REQUIRED",
      ownerOnly: "Owner-only operations",
      deleteBoard: "Delete board",
      deleteBoardBody: "Deletes the board and its cascaded board data. Owner only.",
      transferOwnership: "Transfer ownership",
      transferOwnershipBody: "Moves owner control to another existing board member.",
      deleteConfirmTitle: "Delete {board}",
      deleteConfirmBody: "Type the board name below to confirm permanent deletion. Board members, cards, columns, activity, and invites are removed through cascade rules.",
      transferConfirmTitle: "Transfer ownership",
      transferConfirmBody: "Select another member who should become the board owner. Your role becomes editor after the transfer.",
      confirmBoardName: "Confirm board name",
      newOwner: "New owner",
      deleteConfirmHint: "Type the board name exactly to confirm deletion.",
      chooseAnotherMember: "Choose another board member.",
      boardDeletionFailed: "Board deletion failed.",
      ownershipTransferFailed: "Ownership transfer failed.",
      copyShareLink: "Copy share link",
      createInvite: "Create invite",
      saveSettings: "Save settings",
      ownerControls: "Owner controls",
      defaultInviteRole: "Default invite role",
      viewerMode: "Viewer mode",
      presence: "Presence",
      provider: "Provider",
      syncStatus: "Sync status"
    },
    profile: {
      title: "Profile",
      avatarAndName: "Avatar and name",
      displayName: "Display name",
      avatarFile: "Avatar file",
      avatarUrl: "Avatar URL",
      saveProfile: "Save profile",
      clearAvatar: "Clear avatar",
      accountAccess: "Account access",
      session: "Session",
      avatarSource: "Avatar source",
      noFileSelected: "No file selected",
      chooseAvatar: "Choose avatar",
      storageHint: "If a public Supabase avatar bucket exists, files upload there first. Otherwise, paste a public avatar URL.",
      storageNote: "PNG, JPG, or WebP. Smaller files work best.",
      logoutNote: "Logging out clears the workspace stores, ends the Supabase session, and returns you to the auth page.",
      logoutTitle: "Log out",
      noSupabaseUser: "No Supabase user",
      profileLoadsFromPublicProfiles: "Profile loads from public.profiles",
      supabaseUser: "Supabase user",
      publicProfileEmail: "public.profiles.email",
      activeSession: "ACTIVE",
      userId: "User ID",
      currentRole: "Current role",
      noActiveSession: "No active session",
      profileUrlOrFile: "Profile URL / uploaded file",
      initialsFallback: "Initials fallback"
    },
    members: {
      title: "Members & Roles",
      pageTitle: "{board} members",
      presence: "Realtime member presence",
      roleRules: "Role Rules",
      shareLink: "Share Link",
      inviteMember: "Invite member",
      noCollaborators: "No collaborators yet",
      noCollaboratorsBody: "Only real board_members rows are shown. Use owner-only invitations to add collaborators.",
      noPendingInvites: "No pending invitations",
      noPendingInvitesBody: "Owner-created invitations will appear here.",
      invitesNeedMigration: "Invites require database migration.",
      inviteBody: "The members page still works with existing board_members rows.",
      owner: "Full board control",
      editor: "Create, edit, and move cards",
      viewer: "Read-only access with visible presence",
      activity: "Activity",
      lastAction: "Last action",
      permission: "Permission",
      online: "online",
      offline: "offline",
      onlineMembers: "{count} online",
      presenceLive: "Presence live",
      presenceOffline: "Presence offline",
      presenceConnecting: "Connecting to Supabase presence",
      presenceUnavailable: "Presence unavailable",
      activeSignals: "active editing signal",
      noActiveSignals: "No active editing signals",
      invitedBy: "Invite a member"
    },
    activity: {
      title: "History of Changes",
      body: "Only rows from public.activity_logs are shown here.",
      all: "All",
      cards: "Cards",
      members: "Members",
      conflicts: "Conflicts",
      system: "System",
      noActivity: "No activity",
      noActivityBody: "No Supabase activity log rows match this filter."
    },
    ai: {
      title: "AI assistant",
      body: "Assist the board without exposing secrets.",
      generate: "Generate",
      generating: "Generating...",
      subtasks: "Break card into subtasks",
      priority: "Prioritize board",
      assistantLabel: "AI Assistant",
      openAssistant: "Open full AI Assistant",
      selectedCard: "Card",
      prompt: "Prompt",
      generated: "Generated results",
      generatedSubtasks: "Generated subtasks",
      priorityRecommendations: "Priority recommendations",
      savedChecklist: "Saved checklist items",
      openBoards: "Open boards",
      noBoardSelected: "No board selected",
      noCardsAvailable: "No cards available",
      noGenerated: "No generated results yet",
      noSavedChecklist: "No saved checklist yet",
      saveToCard: "Save to card",
      saving: "Saving...",
      selectCardFirst: "Select a card first",
      noCardsInScope: "{count} cards in scope",
      aiPreparing: "AI is preparing results...",
      aiSaved: "AI subtasks saved to card",
      aiPreparedSubtasks: "AI prepared subtasks",
      aiPreparedPriorities: "AI prepared priority recommendations",
      selectCardFirst: "Select a card first",
      noDescription: "No description provided.",
      chooseModeAndGenerate: "Choose a mode and click Generate. Results are separate from saved checklist items.",
      addCardsFirst: "Add cards to this board before asking AI for subtasks or prioritization.",
      deepSeekNote: "DeepSeek is called only by the Supabase Edge Function. The frontend sends board context, never a provider key."
    },
    messages: {
      inviteCreated: "Invite created for {email}",
      inviteDuplicate: "Invitation for {email} already exists",
      inviteRevoked: "Invite revoked for {email}",
      memberRemoved: "{name} removed",
      roleChanged: "{name} changed to {role}",
      boardOpened: "{name} opened",
      boardCreated: "{name} created",
      profileSaved: "Profile saved",
      profileSaveFailed: "Profile save failed",
      boardDeleted: "Board deleted",
      ownershipTransferred: "Ownership transferred",
      invalidEmailOrPassword: "Invalid email or password.",
      avatarStorageNotConfigured: "Avatar storage is not configured. Create a public Supabase Storage bucket named avatars or paste an Avatar URL.",
      avatarUploadFailed: "Avatar upload failed",
      avatarSaved: "Avatar saved",
      avatarCleared: "Avatar cleared"
    }
  },
  ru: {
    nav: {
      boards: "Доски",
      board: "Доска",
      activity: "Активность",
      members: "Участники",
      settings: "Настройки",
      profile: "Профиль",
      ai: "ИИ"
    },
    common: {
      signIn: "Войти",
      createAccount: "Создать аккаунт",
      forgotPassword: "Забыли пароль",
      signOut: "Выйти",
      save: "Сохранить",
      saving: "Сохранение...",
      close: "Закрыть",
      cancel: "Отмена",
      working: "Выполняется...",
      error: "Ошибка",
      invite: "Пригласить",
      undo: "Отменить",
      redo: "Повторить",
      open: "Открыть",
      create: "Создать",
      remove: "Удалить",
      revoke: "Отозвать",
      delete: "Удалить",
      transfer: "Передать",
      chooseAvatar: "Выбрать аватар",
      clearAvatar: "Очистить аватар",
      noFileSelected: "Файл не выбран",
      descriptionOptional: "Описание необязательно",
      selectBoardMember: "Выберите участника доски",
      selectFirst: "Сначала выберите карточку",
      logoutFailed: "Не удалось выйти",
      unreadNotifications: "Непрочитанных уведомлений: {count}"
    },
    auth: {
      signInTitle: "Войти",
      signInBody: "Войдите через Supabase auth, чтобы попасть в рабочее пространство.",
      registerTitle: "Создать аккаунт",
      registerBody: "Создаёт аккаунт Supabase. public.handle_new_user() должен создать строку профиля.",
      forgotTitle: "Сброс пароля",
      forgotBody: "Запрашивает письмо для сброса пароля Supabase.",
      inviteTitle: "Принять приглашение",
      inviteBody: "Войдите с приглашённым email, затем примите приглашение на доску.",
      formNote: "Это вызывает Supabase auth. Локальные тестовые пользователи не создаются.",
      ownerFullAccess: "Владелец: полный доступ",
      editorCardsOnly: "Редактор: только карточки",
      viewerReadOnly: "Наблюдатель: только чтение",
      email: "Email",
      password: "Пароль",
      name: "Имя",
      resetSent: "Проверьте почту: ссылка для сброса пароля отправлена.",
      invitationAccepted: "Приглашение принято.",
      invalidLogin: "Неверный email или пароль.",
      accountExists: "Аккаунт с таким email уже существует.",
      authFailed: "Ошибка авторизации. Повторите попытку.",
      inviteFailed: "Не удалось принять приглашение. Войдите с приглашённым email."
    },
    boards: {
      header: "Панель рабочего пространства",
      title: "Ваши доски",
      summary: "Здесь показаны доски, загруженные из строк участников Supabase. Пустое рабочее пространство останется пустым, пока вы не создадите доску.",
      setupRequired: "Требуется настройка Supabase",
      setupRequiredBody: "Укажите VITE_SUPABASE_URL и VITE_SUPABASE_ANON_KEY, затем перезагрузите приложение. VITE_SUPABASE_PUBLISHABLE_KEY тоже поддерживается как запасной вариант.",
      profileSetup: "Требуется настроить профиль",
      boardsLoadFailed: "Не удалось загрузить доски",
      noBoards: "Пока нет досок",
      noBoardsBody: "Создайте доску, чтобы добавить доску Supabase, владельца и стандартные колонки.",
      createTitle: "Новая доска",
      createBody: "Создаёт доску, участника-владельца и колонки Todo / In Progress / Review / Done.",
      openBoard: "Открыть доску",
      createBoard: "Создать доску",
      recentActivity: "Последняя активность",
      noRecentActivity: "Нет недавней активности",
      noRecentActivityBody: "Активность появляется после создания строк журналов в Supabase."
    },
    board: {
      notFound: "Доска не найдена",
      workSurface: "Рабочая область доски",
      loading: "Загрузка доски",
      loadingBody: "Читаем доску, колонки, карточки, участников и активность из Supabase.",
      noColumns: "Пока нет колонок",
      noColumnsBody: "У этой доски нет строк колонок Supabase.",
      createDefaultColumns: "Создать стандартные колонки",
      searchPlaceholder: "Поиск по карточкам",
      allAssignees: "Все исполнители",
      allLabels: "Все метки",
      allStatuses: "Все статусы",
      titleField: "Название",
      descriptionField: "Описание",
      columnField: "Колонка",
      assigneeField: "Исполнитель",
      labelsField: "Метки",
      addCard: "Добавить карточку",
      unassigned: "Не назначено",
      newCardTitle: "Название новой карточки",
      newCardDescription: "Что должно произойти?",
      labelsPlaceholder: "frontend, urgent",
      statusActive: "активно",
      statusBlocked: "заблокировано",
      statusDone: "готово",
      taskDetail: "Детали задачи",
      selectTask: "Выберите задачу",
      outdatedEditDetected: "Обнаружено устаревшее редактирование",
      draftBasedOnVersion: "Черновик основан на версии {mine}. Последняя версия — {latest}.",
      keepMine: "Оставить мой вариант",
      acceptLatest: "Принять последнюю версию",
      checklist: "Чеклист",
      noChecklistItems: "Сохранённых пунктов чеклиста пока нет.",
      comments: "Комментарии",
      addComment: "Добавить комментарий",
      addCommentPlaceholder: "Добавьте комментарий",
      history: "История",
      cardHistoryRecorded: "История карточки записывается в журналы активности.",
      noCardsHere: "Здесь пока нет карточек",
      createCardHint: "Создайте карточку или переместите существующую карточку Supabase в {column}.",
      viewerReadOnlyShort: "Роль viewer доступна только для чтения. Действия с карточками отключены.",
      online: "ОНЛАЙН",
      offlinePrefix: "ОФЛАЙН",
      connectionRestored: "Соединение восстановлено. Очередь синхронизируется.",
      connectionLost: "Нет соединения. Новые действия будут поставлены в очередь.",
      versionConflict: "Конфликт версии: карточка уже изменена другим пользователем",
      cardMoveFailed: "Не удалось переместить карточку",
      cardCreationFailed: "Не удалось создать карточку",
      cardQueuedOffline: "Карточка поставлена в очередь офлайн",
      cardSaveFailed: "Не удалось сохранить карточку",
      changeQueuedOffline: "Изменение поставлено в очередь офлайн",
      deleteQueuedOffline: "Удаление поставлено в очередь офлайн",
      commentFailed: "Не удалось сохранить комментарий",
      commentAdded: "Комментарий добавлен",
      commentUpdated: "Комментарий обновлён",
      commentDeleted: "Комментарий удалён",
      status: "Статус",
      saveCard: "Сохранить карточку",
      deleteCard: "Удалить",
      noCardSelected: "Карточка не выбрана",
      viewerReadOnly: "Роль viewer доступна только для чтения. Редактирование, удаление, перемещение и комментарии отключены."
    },
    settings: {
      title: "Операционные настройки для {board}.",
      subtitle: "Подключёнными отмечены только данные, поддержанные предоставленной схемой Supabase.",
      systemControlCenter: "Центр управления Realtime",
      boardSection: "Доска",
      invitationsSection: "Приглашения",
      permissionsSection: "Права",
      localizationSection: "Локализация",
      realtimeSection: "Realtime",
      workspaceIdentity: "Идентификация рабочего пространства",
      pendingAccess: "Ожидающий доступ",
      roleEnforcement: "Проверка ролей",
      interfaceLanguage: "Язык интерфейса",
      languageEnglish: "English",
      languageRussian: "Русский",
      languageEnglishDetail: "Интерфейс на английском",
      languageRussianDetail: "Интерфейс на русском",
      languagePreference: "Язык сохраняется локально.",
      liveSync: "Канал живой синхронизации",
      conflictStrategy: "Стратегия конфликтов",
      conflictStrategyVersioned: "Версионированный last-write-wins с откатом",
      conflictStrategyManual: "Ручной разбор конфликтов",
      conflictStrategyServer: "Режим авторитетного сервера",
      conflictStrategyVersionedDetail: "Предпочитать последнюю версию с откатом",
      conflictStrategyManualDetail: "Показывать ручной разбор при конфликте записей",
      conflictStrategyServerDetail: "Позволить серверу решить итоговую запись",
      realtime: "Realtime",
      realtimeProvider: "Провайдер",
      realtimeStatus: "Статус синхронизации",
      realtimePresence: "Presence",
      realtimeLive: "Supabase Realtime",
      realtimeFallback: "Локальный запасной канал BroadcastChannel",
      boardUrl: "URL доски",
      privateToMembers: "Только для участников",
      synced: "СИНХРОНИЗИРОВАНО",
      connected: "ПОДКЛЮЧЕНО",
      versioned: "ВЕРСИОНИРОВАНО",
      languageSynced: "ЯЗЫК СИНХРОНИЗИРОВАН",
      rlsRequired: "ТРЕБУЕТСЯ ПОЛИТИКА RLS",
      ownerOnly: "Операции только для владельца",
      deleteBoard: "Удалить доску",
      deleteBoardBody: "Удаляет доску и все связанные данные. Только для владельца.",
      transferOwnership: "Передать владение",
      transferOwnershipBody: "Передаёт права владельца другому существующему участнику доски.",
      deleteConfirmTitle: "Удалить {board}",
      deleteConfirmBody: "Введите точное название доски ниже, чтобы подтвердить безвозвратное удаление. Участники, карточки, колонки, активность и приглашения удалятся каскадом.",
      transferConfirmTitle: "Передать владение",
      transferConfirmBody: "Выберите другого участника, который станет владельцем доски. После передачи ваша роль станет editor.",
      confirmBoardName: "Подтвердите название доски",
      newOwner: "Новый владелец",
      deleteConfirmHint: "Введите точное название доски, чтобы подтвердить удаление.",
      chooseAnotherMember: "Выберите другого участника доски.",
      boardDeletionFailed: "Не удалось удалить доску.",
      ownershipTransferFailed: "Не удалось передать владение.",
      copyShareLink: "Скопировать ссылку",
      createInvite: "Создать приглашение",
      saveSettings: "Сохранить настройки",
      ownerControls: "Управление владельца",
      defaultInviteRole: "Роль по умолчанию",
      viewerMode: "Режим viewer",
      presence: "Presence",
      provider: "Провайдер",
      syncStatus: "Статус синхронизации"
    },
    profile: {
      title: "Профиль",
      avatarAndName: "Аватар и имя",
      displayName: "Отображаемое имя",
      avatarFile: "Файл аватара",
      avatarUrl: "URL аватара",
      saveProfile: "Сохранить профиль",
      clearAvatar: "Очистить аватар",
      accountAccess: "Доступ к аккаунту",
      session: "Сессия",
      avatarSource: "Источник аватара",
      noFileSelected: "Файл не выбран",
      chooseAvatar: "Выбрать аватар",
      storageHint: "Если есть публичный бакет Supabase для аватаров, файлы сначала загружаются туда. Иначе вставьте публичный URL аватара.",
      storageNote: "PNG, JPG или WebP. Меньшие файлы работают лучше.",
      logoutNote: "Выход очищает рабочие сторы, завершает сессию Supabase и возвращает на страницу авторизации.",
      logoutTitle: "Выйти",
      noSupabaseUser: "Пользователь Supabase не найден",
      profileLoadsFromPublicProfiles: "Профиль загружается из public.profiles",
      supabaseUser: "Пользователь Supabase",
      publicProfileEmail: "public.profiles.email",
      activeSession: "АКТИВНО",
      userId: "ID пользователя",
      currentRole: "Текущая роль",
      noActiveSession: "Нет активной сессии",
      profileUrlOrFile: "URL профиля / загруженный файл",
      initialsFallback: "Инициалы по умолчанию"
    },
    members: {
      title: "Участники и роли",
      pageTitle: "Участники доски {board}",
      presence: "Онлайн участников в реальном времени",
      roleRules: "Правила ролей",
      shareLink: "Ссылка для доступа",
      inviteMember: "Пригласить участника",
      noCollaborators: "Пока нет участников",
      noCollaboratorsBody: "Показываются только реальные строки board_members. Добавляйте участников через приглашения владельца.",
      noPendingInvites: "Нет ожидающих приглашений",
      noPendingInvitesBody: "Здесь появятся приглашения, созданные владельцем.",
      invitesNeedMigration: "Для приглашений нужна миграция базы.",
      inviteBody: "Страница участников продолжает работать с существующими строками board_members.",
      owner: "Полный контроль доски",
      editor: "Создаёт, редактирует и двигает карточки",
      viewer: "Только чтение с видимым presence",
      activity: "Активность",
      lastAction: "Последнее действие",
      permission: "Права",
      online: "онлайн",
      offline: "офлайн",
      onlineMembers: "{count} онлайн",
      presenceLive: "Presence активно",
      presenceOffline: "Presence отключён",
      presenceConnecting: "Подключение к presence Supabase",
      presenceUnavailable: "Presence недоступен",
      activeSignals: "активный сигнал редактирования",
      noActiveSignals: "Нет активных сигналов редактирования",
      invitedBy: "Пригласить участника"
    },
    activity: {
      title: "История изменений",
      body: "Здесь показываются только строки public.activity_logs.",
      all: "Все",
      cards: "Карточки",
      members: "Участники",
      conflicts: "Конфликты",
      system: "Система",
      noActivity: "Нет активности",
      noActivityBody: "Для этого фильтра нет строк activity_logs из Supabase."
    },
    ai: {
      title: "ИИ-помощник",
      body: "Помогает доске, не раскрывая секреты.",
      generate: "Сгенерировать",
      generating: "Генерация...",
      subtasks: "Разбить карточку на подзадачи",
      priority: "Приоритизировать доску",
      assistantLabel: "ИИ-помощник",
      openAssistant: "Открыть ИИ-помощник",
      selectedCard: "Карточка",
      prompt: "Промпт",
      generated: "Сгенерированные результаты",
      generatedSubtasks: "Сгенерированные подзадачи",
      priorityRecommendations: "Рекомендации по приоритетам",
      savedChecklist: "Сохранённые пункты чеклиста",
      openBoards: "Открыть доски",
      noBoardSelected: "Доска не выбрана",
      noCardsAvailable: "Карточек нет",
      noGenerated: "Пока нет результатов",
      noSavedChecklist: "Пока нет сохранённого чеклиста",
      saveToCard: "Сохранить в карточку",
      saving: "Сохранение...",
      selectCardFirst: "Сначала выберите карточку",
      noCardsInScope: "В области {count} карточек",
      aiPreparing: "ИИ готовит результат...",
      aiSaved: "ИИ-подзадачи сохранены в карточку",
      aiPreparedSubtasks: "ИИ подготовил подзадачи",
      aiPreparedPriorities: "ИИ подготовил рекомендации по приоритетам",
      selectCardFirst: "Сначала выберите карточку",
      noDescription: "Описание не указано.",
      chooseModeAndGenerate: "Выберите режим и нажмите Generate. Результаты отделены от сохранённых пунктов чеклиста.",
      addCardsFirst: "Сначала добавьте карточки на доску, затем спрашивайте ИИ о подзадачах или приоритизации.",
      deepSeekNote: "DeepSeek вызывается только через Supabase Edge Function. Фронтенд отправляет контекст доски, но не ключ провайдера."
    },
    messages: {
      inviteCreated: "Приглашение создано для {email}",
      inviteDuplicate: "Приглашение для {email} уже существует",
      inviteRevoked: "Приглашение отозвано для {email}",
      memberRemoved: "{name} удалён",
      roleChanged: "Роль {name} изменена на {role}",
      boardOpened: "{name} открыта",
      boardCreated: "{name} создана",
      profileSaved: "Профиль сохранён",
      profileSaveFailed: "Не удалось сохранить профиль",
      boardDeleted: "Доска удалена",
      ownershipTransferred: "Владение передано",
      invalidEmailOrPassword: "Неверный email или пароль.",
      avatarStorageNotConfigured: "Хранилище аватаров не настроено. Создайте публичный бакет Supabase Storage с именем avatars или вставьте Avatar URL.",
      avatarUploadFailed: "Не удалось загрузить аватар",
      avatarSaved: "Аватар сохранён",
      avatarCleared: "Аватар очищен"
    }
  }
};

function savedLanguage() {
  if (typeof window === "undefined") return "en";
  return window.localStorage.getItem(STORAGE_KEY) || "en";
}

export const language = ref(savedLanguage());

function applyLanguage(nextLanguage) {
  const next = nextLanguage === "ru" ? "ru" : "en";
  language.value = next;
  if (typeof window !== "undefined") {
    window.localStorage.setItem(STORAGE_KEY, next);
    if (window.document?.documentElement) window.document.documentElement.lang = next;
  }
}

watch(language, (next) => {
  applyLanguage(next);
}, { immediate: true });

function resolveMessage(path, locale) {
  const parts = path.split(".");
  let node = messages[locale];
  for (const part of parts) node = node?.[part];
  return node;
}

export function t(path, params = {}) {
  const active = resolveMessage(path, language.value) ?? resolveMessage(path, "en") ?? path;
  if (typeof active !== "string") return path;
  return active.replace(/\{(\w+)\}/g, (_match, key) => String(params[key] ?? ""));
}

export function setLanguage(nextLanguage) {
  applyLanguage(nextLanguage);
}

export function useLocalization() {
  return {
    language,
    t,
    setLanguage,
    isRussian: computed(() => language.value === "ru")
  };
}
